### ISSUE TITLE
Minor Spacing Item

### ISSUE THREAD

**Issue by aheber** [xixiaofinland/afmt#15]
You can discard this if this is intentional. Given that you've added spaces in many places it feels like you'd prefer to format this differently.

The parenthesis of trigger events is placed directly against the target object. I would have expected it to have a space.

Example:
```apex
trigger TestTrigger on Account (after insert) {}
```

Formatted:
```apex
trigger TestTrigger on Account(after insert) {
}
```

**Comment by xixiaofinland** [comment]
This is an interesting one, I quickly matched PA without thinking much.

in [PA playground](https://apex.dangmai.net/), it is this result.  Let me fire an issue in PA to see what Dang says.

```
trigger TestTrigger on Account(after insert) {
}
```

**Comment by aheber** [comment]
Thanks for checking on that. I think in my mind this was closer to an `if` statement than a method call.
