### ISSUE TITLE
SOQL Group By fields should be joined on comma

### ISSUE THREAD

**Issue by aheber** [xixiaofinland/afmt#21]
SOQL Group By clauses have a few different types of nodes. A Having clause should be connected with a space (as it is today) but the list of fields to join on should be connected to each other with commas.

Example:
```apex
class T {
  {
    [SELECT Id FROM Account GROUP BY Id];
    [SELECT Id FROM Account GROUP BY Id, Name];
    [SELECT Id FROM Account GROUP BY Id, Name HAVING COUNT(Id) > 2];
  }
}
```

Formatted:
```apex
class T {
  {
    [SELECT Id FROM Account GROUP BY Id];
    [SELECT Id FROM Account GROUP BY Id Name];
    [SELECT Id FROM Account GROUP BY Id Name HAVING COUNT(Id) > 2];
  }
}
```

**Comment by aheber** [comment]
I'll submit a PR for this one.

**Comment by xixiaofinland** [comment]
fixed in https://github.com/xixiaofinland/afmt/pull/22
Thanks @aheber
