### ISSUE TITLE
Release should include Apple Silicon (arm64) binary 

### ISSUE THREAD

**Issue by aheber** [xixiaofinland/afmt#4]
The existing release process includes MacOS x86_64 binary. It would be great if it could also include a binary optimized for amd64/Apple Silicon. This would allow it to be more performant on that platform as it has to go through a translation layer right now.

It is possible to compile one binary that includes code optimized for both platforms. This is known as "fat binaries" or "universal binaries" it would bloat the download size but I personally wouldn't be very worried about that as an occasional download that I'm keeping on my personal machine.

**Comment by xixiaofinland** [comment]
amd64/Apple Silicon binary was added since [release v0.0.12 ](https://github.com/xixiaofinland/afmt/releases/tag/v0.0.12)

**Comment by aheber** [comment]
Great!! I just tested it and it is working on my machine.

The Intel binary formatted my largest file in ~300ms and the Apple Silicon in ~220ms (as low as ~200)

My smaller file test was ~17ms on Intel and ~3ms on Apple Silicon.

All of those are small numbers but that time would really add up across an entire project.

Thank you very much!

**Comment by xixiaofinland** [comment]
Cool!
Once we need to handle multiple files or a entire project, multi-threading in this scenario is a perfect fit and Rust shines in handling it. We will see how it goes in the future :)

**Comment by aheber** [comment]
Yes! Very excited to see it.
